### ISSUE TITLE
Flavor of Linux

### ISSUE THREAD

**Issue by Colorfingers** [makehuman-js/makehuman-data#4]
What distribution and version of Linux are you using to run the notebooks?  I am having a hell of problems using Ubuntu 18.04.  Any tips?

Thank you...

**Comment by wassname** [comment]
Still a problem? I used Ubuntu 18.04, python3.5, let me know the error and maybe I can give you more info like exact package versions etc.

**Comment by Colorfingers** [comment]
Thanks Mike... I could not get it to work properly on 18.04 but I loaded 16.04 and used Anaconda instead of loading packages individually.  It kind of worked when exporting proxies but it crashes at the end and leaves the newly created json and supporting files in the tmp folder.  I'll try again later with 18.04.  I think I have an idea now what I may have done incorrectly there.

**Comment by wassname** [comment]
No worries, feel free to ask questions, there's no one else here and I'm happy to help. Just give me details so I can debug it.
