### ISSUE TITLE
Bitbucket repository of makehuman-commandline no longer available

### ISSUE THREAD

**Issue by AlyanQ** [makehuman-js/makehuman-data#6]
The bitbucket repo of makehuman-commandline is no longer available since mercurial has shut down. There is a makehuman-commandline repository on github (https://github.com/severin-lemaignan/makehuman-commandline.git) but it is written in python2.7, whereas makehuman-data requires python3.5 as you mentioned in another issue. I have tried installing an archived version of the mercurial makehuman-commandline repo but to no avail. Could you please share the makehuman-commandline repo that we need to use for this project or let us know how to install the archived version? Thanks for your work.

**Comment by wassname** [comment]
I don't have a local copy I'm afraid.

I'm the notebooks in this repository, you can see the kernal I was using was python2.7, so perhaps that is the right version.

![image](https://user-images.githubusercontent.com/1103714/147896641-9a44987a-8703-4307-bf23-5d8e27ee6aa4.png)

I also found this version that might be helpfull: https://bitbucket.org/duststorm01/makehuman-commandline-git/commits/

**Comment by AlyanQ** [comment]
Thank you for your reply, you mentioned here https://github.com/makehuman-js/makehuman-data/issues/4#issuecomment-508893447 that you were using python3.5 which confused me. I am now using Python 2.7 and it is working fine for now. Thank you for your work!
